FROM percona:5.7
MAINTAINER Traian Munteanu <munteanutraian@gmail.com>

COPY ./cnf/my.cnf /etc/mysql/my.cnf

ENV MYSQL_ROOT_PASSWORD boozt
ENV MYSQL_DATABASE boozt
ENV MYSQL_USER boozt
ENV MYSQL_PASSWORD boozt


